Login
Sistemas-Gerenciamento-Projetos/siswebgp-frontend pull request #10
Opened 2023-04-19 23:55 UTC by Sistemas-Gerenciamento-Projetos

2023-04-20 00:07 UTC, Sistemas-Gerenciamento-Projetos commented
Apenas correções de aspas simples e duplas, funções do registre-se.

2023-04-20 00:17 UTC, Eduard0Ferreira approved these changes

2023-04-20 00:17 UTC, Eduard0Ferreira approved these changes

2023-04-20 00:27 UTC, Sistemas-Gerenciamento-Projetos reviewed
Feat: Validação da senha na página de cadastre-se

2023-04-20 00:40 UTC, Eduard0Ferreira requested changes
Correções na tela de cadastro

2023-05-08 13:00 UTC, Sistemas-Gerenciamento-Projetos commented
Ultimas modificações.

2023-05-08 13:00 UTC, closed without merging